# Generated by Django 3.1.7 on 2021-05-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_group', models.CharField(max_length=255, verbose_name='Grupo de Alimentos')),
                ('food', models.CharField(max_length=255, verbose_name='Alimento')),
                ('amount', models.FloatField(default=0, verbose_name='Cantidad')),
                ('unit', models.CharField(max_length=255, verbose_name='Unidad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Agregado')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='ger',
            name='ger',
            field=models.FloatField(default=0, verbose_name='Requerimiento Energético en Reposo'),
        ),
        migrations.AlterField(
            model_name='ger',
            name='get',
            field=models.FloatField(default=0, verbose_name='Requerimiento Energético Total'),
        ),
        migrations.AlterField(
            model_name='imc',
            name='imc',
            field=models.FloatField(default=0, verbose_name='IMC'),
        ),
        migrations.AlterField(
            model_name='pesocorregido',
            name='corrected_weight',
            field=models.FloatField(default=0, verbose_name='Peso Corregido'),
        ),
    ]
