# Generated by Django 3.1.7 on 2021-04-23 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cita')),
                ('commentary', models.TextField(blank=True, max_length=150, null=True, verbose_name='Comentario de Cita')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cita', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['commentary'],
            },
        ),
    ]
