# Generated by Django 3.1.7 on 2021-05-06 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesoCorregido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrected_weight', models.FloatField(verbose_name='Peso Corregido')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Calculo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesocorregido', to='registration.profile')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='IMC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imc', models.FloatField(verbose_name='IMC')),
                ('weight_level', models.CharField(max_length=30, verbose_name='Nivel de Peso')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Calculo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imc', to='registration.profile')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='GER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ger', models.FloatField(verbose_name='Requerimiento Energético en Reposo')),
                ('get', models.FloatField(verbose_name='Requerimiento Energético Total')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Calculo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ger', to='registration.profile')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
