# Generated by Django 3.1.7 on 2021-04-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='hour',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de la cita'),
        ),
    ]
