# Generated by Django 3.1.7 on 2021-05-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_appointment_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de cita'),
        ),
    ]
