# Generated by Django 3.1.7 on 2021-04-08 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name_m', models.CharField(blank=True, max_length=150, null=True, verbose_name='Segundo Apellido')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='Teléfono')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=registration.models.custom_upload_to, verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biografia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
